### ISSUE TITLE
About loading spatialite

### ISSUE THREAD

**Issue by aborruso** [simonw/sqlite-utils#188]
Hi @simonw ,
If I run

```
sqlite3
.load /usr/local/lib/mod_spatialite.so
select spatialite_version();
```

I have `5.0.0`.

![image](https://user-images.githubusercontent.com/30607/96332706-d8cd3300-1065-11eb-906b-daf99963198e.png)

If I run

```
sqlite-utils :memory: "select spatialite_version()" --load-extension=spatialite
```

I have

```
Traceback (most recent call last):
  File "/home/aborruso/.local/bin/sqlite-utils", line 8, in <module>
    sys.exit(cli())
  File "/home/aborruso/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/aborruso/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/aborruso/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aborruso/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aborruso/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/aborruso/.local/lib/python3.8/site-packages/sqlite_utils/cli.py", line 936, in query
    _load_extensions(db, load_extension)
  File "/home/aborruso/.local/lib/python3.8/site-packages/sqlite_utils/cli.py", line 1326, in _load_extensions
    db.conn.load_extension(ext)
TypeError: argument 1 must be str, not None
```

How to load properly spatialite extension in sqlite-utils?

Thank you very muc

**Comment by aborruso** [comment]
I have done a stupid question.

If I run

```
sqlite-utils :memory: "select spatialite_version()" --load-extension=/usr/local/lib/mod_spatialite.so
```

I have `[{"spatialite_version()": "5.0.0"}]`

Thank you for this great tool
