### ISSUE TITLE
Better error message if `--convert` code fails to return a dict

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#363]
Here's the traceback if your `--convert` function doesn't return a dict right now:
```
% sqlite-utils insert /tmp/all.db blah /tmp/log.log --convert 'all.upper()' --all         

Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/bin/sqlite-utils", line 33, in <module>
    sys.exit(load_entry_point('sqlite-utils', 'console_scripts', 'sqlite-utils')())
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/cli.py", line 949, in insert
    insert_upsert_implementation(
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/cli.py", line 834, in insert_upsert_implementation
    db[table].insert_all(
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/db.py", line 2602, in insert_all
    first_record = next(records)
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/db.py", line 3044, in fix_square_braces
    for record in records:
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/cli.py", line 831, in <genexpr>
    docs = (decode_base64_values(doc) for doc in docs)
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/utils.py", line 86, in decode_base64_values
    to_fix = [
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/utils.py", line 89, in <listcomp>
    if isinstance(doc[k], dict)
TypeError: string indices must be integers
```
It would be nicer if that returned a more useful error message.

_Originally posted by @simonw in https://github.com/simonw/sqlite-utils/issues/361#issuecomment-1006295276_

**Comment by simonw** [comment]
This check should run inside the `.insert_all()` method. It should raise a custom exception which the CLI code can then catch and turn into a click error.

**Comment by simonw** [comment]
As part of this work I should add test coverage of this error message too: https://github.com/simonw/sqlite-utils/blob/413f8ed754e38d7b190de888c85fe8438336cb11/sqlite_utils/cli.py#L826

**Comment by simonw** [comment]
> This check should run inside the `.insert_all()` method. It should raise a custom exception which the CLI code can then catch and turn into a click error.

Actually no that doesn't work, because this line causes an error before we even get to `.insert_all()`:

https://github.com/simonw/sqlite-utils/blob/7d928f83085fb285f294dbdaeb93fd94a44d5d44/sqlite_utils/cli.py#L1012-L1013

**Comment by simonw** [comment]
Demos:
```
% sqlite-utils insert /tmp/all.db blah /tmp/log.log --convert '[1]' --text
Error: Rows must all be dictionaries, got: 1
% sqlite-utils insert /tmp/all.db blah /tmp/log.log --convert '1' --text             
Error: --convert must return dict or iterator
```
