### ISSUE TITLE
`deterministic=True` fails on versions of SQLite prior to 3.8.3

### ISSUE THREAD

**Issue by learning4life** [simonw/sqlite-utils#408]
Hi, love your work.

I am unable to lookup indexes in a database using sqlite-utils:

`
sqlite-utils indexes city_spec.db --table`

or

`sqlite-utils indexes city_spec.db MyTable
`

**Software**
sqlite-utils, version 3.24
sqlite3 --version: 3.36.0 

**Output:**

Traceback (most recent call last):
  File "/opt/app-root/bin/sqlite-utils", line 8, in <module>
    sys.exit(cli())
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlite_utils/cli.py", line 2123, in indexes
    ctx.invoke(
  File "/opt/app-root/lib64/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlite_utils/cli.py", line 1624, in query
    db.register_fts4_bm25()
  File "/opt/app-root/lib64/python3.8/site-packages/sqlite_utils/db.py", line 403, in register_fts4_bm25
    self.register_function(rank_bm25, deterministic=True)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlite_utils/db.py", line 399, in register_function
    register(fn)
  File "/opt/app-root/lib64/python3.8/site-packages/sqlite_utils/db.py", line 392, in register
    self.conn.create_function(name, arity, fn, **kwargs)
sqlite3.NotSupportedError: deterministic=True requires SQLite 3.8.3 or higher

**Comment by simonw** [comment]
I thought I'd made it so `deterministic=True` would be silently ignored in environments that don't support it, but clearly I missed a case here!

**Comment by simonw** [comment]
Here's the code in question:

https://github.com/simonw/sqlite-utils/blob/521921b849003ed3742338f76f9d47ff3d95eaf3/sqlite_utils/db.py#L384-L394

It's checking for Python 3.8, because that's the version of Python that added the `deterministic=True` option: https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function

But from your error message it looks like it should be checking the SQLite version too.

**Comment by simonw** [comment]
Here's the SQLite changelog mentioning that it was added in 3.8.3: https://www.sqlite.org/changes.html#version_3_8_3

**Comment by simonw** [comment]
I need a `db.sqlite_version` property to implement this check.

**Comment by learning4life** [comment]
Thanks @simonw 

I will test it after my vacation 👍

**Comment by learning4life** [comment]
@simonw 

Now I get this:

`(app-root) sqlite-utils indexes global.db --table
Error: near "(": syntax error
(app-root) sqlite-utils --version
sqlite-utils, version 3.25.1
(app-root) sqlite3 --version
3.36.0 2021-06-18 18:36:39
`
