### ISSUE TITLE
Convert with `--multi` and `--dry-run` flag does not work

### ISSUE THREAD

**Issue by dotcs** [simonw/sqlite-utils#415]
It's not possible to combine `--multi` and `--dry-run` flag in the `convert` command.

Let's first create a simple database from JSON string

```console
$ echo '[{"foo": "abc"}]' | sqlite-utils insert demo.db demo -
$ sqlite-utils query demo.db "SELECT * FROM demo"             
[{"foo": "abc"}]
```

and then try to convert the "foo" column with a static value "bar" (see docs [Converting a column into multiple columns](https://sqlite-utils.datasette.io/en/stable/cli.html#converting-a-column-into-multiple-columns))

```console
$ sqlite-utils convert demo.db demo foo '{"foo": "bar"}' --multi --dry-run
Traceback (most recent call last):
  File "/home/dotcs/anaconda3/envs/tools/bin/sqlite-utils", line 8, in <module>
    sys.exit(cli())
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/dotcs/anaconda3/envs/tools/lib/python3.9/site-packages/sqlite_utils/cli.py", line 2686, in convert
    for row in db.conn.execute(sql, where_args).fetchall():
sqlite3.OperationalError: user-defined function raised exception
```

But without the `--dry-run` flag it does work as expected:

```console
$ sqlite-utils convert demo.db demo foo '{"foo": "bar"}' --multi
$ sqlite-utils query demo.db "SELECT * FROM demo"               
[{"foo": "bar"}]
```

```console
$ sqlite-utils --version
sqlite-utils, version 3.25.1
```

**Comment by simonw** [comment]
Thanks for the really clear steps to reproduce!

**Comment by simonw** [comment]
I can fix this like so:
```
% sqlite-utils convert demo.db demo foo '{"foo": "bar"}' --multi --dry-run
abc
 --- becomes:
{"foo": "bar"}

Would affect 1 row
```
Diff is this:
```diff
diff --git a/sqlite_utils/cli.py b/sqlite_utils/cli.py
index 0cf0468..b2a0440 100644
--- a/sqlite_utils/cli.py
+++ b/sqlite_utils/cli.py
@@ -2676,7 +2676,10 @@ def convert(
         raise click.ClickException(str(e))
     if dry_run:
         # Pull first 20 values for first column and preview them
-        db.conn.create_function("preview_transform", 1, lambda v: fn(v) if v else v)
+        preview = lambda v: fn(v) if v else v
+        if multi:
+            preview = lambda v: json.dumps(fn(v), default=repr) if v else v
+        db.conn.create_function("preview_transform", 1, preview)
         sql = """
             select
                 [{column}] as value,
```
