### ISSUE TITLE
Silent crash

### ISSUE THREAD

**Issue by frafra** [simonw/sqlite-utils#439]
```
wget "https://artsdatabanken.no/Fab2018/api/export/csv"
sqlite-utils create-database test.db
sqlite-utils insert --csv --delimiter ";" --encoding "utf-16-le" test test.db csv 
  [------------------------------------]    0%
  [#################-------------------]   49%  00:00:01
```
I would like to highlight various issues:
1. sqlite-utils catches exceptions, so there is no easy way to use `pdb` or similar to debug the program; solution: re-raise the exception after handling, or print the stacktrace, or add a debug option
2. The terminal loses its cursor when something unexpected happen, so `reset` is needed; solution: always remove/undo terminal settings when closing
3. Silent crash: this is related to (1.), and it happens when there is a catch-all mechanism; solution: let the program fail.

**Comment by simonw** [comment]
I can't figure out why that error is being swallowed like that. The most likely culprit was this code: 

https://github.com/simonw/sqlite-utils/blob/1b09538bc6c1fda773590f3e600993ef06591041/sqlite_utils/cli.py#L1021-L1043

But I tried changing it like this:

```diff
diff --git a/sqlite_utils/cli.py b/sqlite_utils/cli.py
index 86eddfb..ed26fdd 100644
--- a/sqlite_utils/cli.py
+++ b/sqlite_utils/cli.py
@@ -1023,6 +1023,7 @@ def insert_upsert_implementation(
             docs, pk=pk, batch_size=batch_size, alter=alter, **extra_kwargs
         )
     except Exception as e:
+        raise
         if (
             isinstance(e, sqlite3.OperationalError)
             and e.args
```
And your steps to reproduce still got to 49% and then failed silently.

**Comment by simonw** [comment]
I have a hunch that this crash may be caused by a CSV value which is too long, as addressed at the library level in:
- #440

But not yet addressed in the CLI tool, see:

- #444

**Comment by simonw** [comment]
Maybe this isn't a CSV field value problem - I tried this patch and didn't seem to hit the new breakpoints:
```diff
diff --git a/sqlite_utils/utils.py b/sqlite_utils/utils.py
index d2ccc5f..f1b823a 100644
--- a/sqlite_utils/utils.py
+++ b/sqlite_utils/utils.py
@@ -204,13 +204,17 @@ def _extra_key_strategy(
         # DictReader adds a 'None' key with extra row values
         if None not in row:
             yield row
-        elif ignore_extras:
+            continue
+        else:
+            breakpoint()
+        if ignore_extras:
             # ignoring row.pop(none) because of this issue:
             # https://github.com/simonw/sqlite-utils/issues/440#issuecomment-1155358637
             row.pop(None)  # type: ignore
             yield row
         elif not extras_key:
             extras = row.pop(None)  # type: ignore
+            breakpoint()
             raise RowError(
                 "Row {} contained these extra values: {}".format(row, extras)
             )
```

**Comment by simonw** [comment]
Tried this:
```
% python -i $(which sqlite-utils) insert --csv --delimiter ";" --encoding "utf-16-le" test test.db csv
  [------------------------------------]    0%
  [#################-------------------]   49%  00:00:01Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1072, in main
    ctx.exit()
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 692, in exit
    raise Exit(code)
click.exceptions.Exit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/bin/sqlite-utils", line 33, in <module>
    sys.exit(load_entry_point('sqlite-utils', 'console_scripts', 'sqlite-utils')())
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/sqlite-utils-C4Ilevlm/lib/python3.8/site-packages/click/core.py", line 1090, in main
    sys.exit(e.exit_code)
SystemExit: 0
>>> 
```

**Comment by simonw** [comment]
Wait! The arguments in that are the wrong way round. This is correct:

    sqlite-utils insert --csv --delimiter ";" --encoding "utf-16-le" test.db test csv

It still outputs the following:

  [------------------------------------]    0%
  [#################-------------------]   49%  00:00:02%

But it creates a `test.db` file that is 6.2MB.

That database has 3141 rows in it:

```
% sqlite-utils tables test.db --counts -t
table      count
-------  -------
test        3142
```
I converted that `csv` file to utf-8 like so:

    iconv -f UTF-16LE -t UTF-8 csv > utf8.csv

And it contains 3142 lines:
```
% wc -l utf8.csv 
    3142 utf8.csv
```
So my hunch here is that the problem is actually that the progress bar doesn't know how to correctly measure files in `utf-16-le` encoding!

**Comment by simonw** [comment]
TIL how to use `iconv`: https://til.simonwillison.net/linux/iconv

**Comment by simonw** [comment]
Here's the code that implements the progress bar in question: https://github.com/simonw/sqlite-utils/blob/1b09538bc6c1fda773590f3e600993ef06591041/sqlite_utils/cli.py#L918-L932

**Comment by simonw** [comment]
Yes, this is the problem. The progress bar length is set to the length in bytes of the file - `os.path.getsize(file.name)` - but it's then incremented by the length of each DECODED line in turn (I think this may also exclude newlines?)

**Comment by simonw** [comment]
I'm going to mark this as "help wanted" and leave it open. I'm glad that it's not actually a bug where errors get swallowed.

**Comment by simonw** [comment]
I tried fixing this by using `.tell()` to read the file position as I was iterating through it:
```diff
diff --git a/sqlite_utils/utils.py b/sqlite_utils/utils.py
index d2ccc5f..29ad12e 100644
--- a/sqlite_utils/utils.py
+++ b/sqlite_utils/utils.py
@@ -149,10 +149,13 @@ class UpdateWrapper:
     def __init__(self, wrapped, update):
         self._wrapped = wrapped
         self._update = update
+        self._tell = wrapped.tell()
 
     def __iter__(self):
         for line in self._wrapped:
-            self._update(len(line))
+            tell = self._wrapped.tell()
+            self._update(self._tell - tell)
+            self._tell = tell
             yield line
 ```
This did not work - I get this error:

```
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/utils.py", line 206, in _extra_key_strategy
    for row in reader:
  File "/Users/simon/Dropbox/Development/sqlite-utils/sqlite_utils/utils.py", line 156, in __iter__
    tell = self._wrapped.tell()
OSError: telling position disabled by next() call
```
It looks like you can't use `.tell()` during iteration: https://stackoverflow.com/questions/29618936/how-to-solve-oserror-telling-position-disabled-by-next-call
