### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get' for flake8 on Python 3.7

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#550]
https://github.com/simonw/sqlite-utils/actions/runs/5039064797/jobs/9036965488

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.16/x64/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/opt/hostedtoolcache/Python/3.7.16/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
Error: Process completed with exit code 1.
```

**Comment by simonw** [comment]
This is blocking:
- #549

**Comment by simonw** [comment]
Relevant issues:
- https://github.com/python/importlib_metadata/issues/406
- https://github.com/PyCQA/flake8/issues/1701

It looks to me like this is only a problem for `flake8` on Python 3.7 - 3.8 and higher work OK.

**Comment by simonw** [comment]
Tests passed here: https://github.com/simonw/sqlite-utils/actions/runs/5039119716
