### ISSUE TITLE
Don't crash with a weird numpy version and "no attribute int8"

### ISSUE THREAD

**Issue by simonw** [simonw/sqlite-utils#632]
> I've seen this too. It's really frustrating. I think the solution may be to add `numpy` as an explicit Homebrew dependency to avoid this from happening.
>
> I'm going to fix this in `sqlite-utils` itself.

_Originally posted by @simonw in https://github.com/simonw/llm/issues/531#issuecomment-2237236445_

**Comment by simonw** [comment]
This bug showed up in LLM installed via Homebrew, but the core problem is this:

```
❯ llm --help
Traceback (most recent call last):
  File "/usr/local/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/usr/local/Cellar/llm/0.14/libexec/lib/python3.12/site-packages/llm/__init__.py", line 16, in <module>
    from .embeddings import Collection
  File "/usr/local/Cellar/llm/0.14/libexec/lib/python3.12/site-packages/llm/embeddings.py", line 7, in <module>
    from sqlite_utils import Database
  File "/usr/local/Cellar/llm/0.14/libexec/lib/python3.12/site-packages/sqlite_utils/__init__.py", line 4, in <module>
    from .db import Database
  File "/usr/local/Cellar/llm/0.14/libexec/lib/python3.12/site-packages/sqlite_utils/db.py", line 211, in <module>
    np.int8: "INTEGER",
    ^^^^^^^
AttributeError: module 'numpy' has no attribute 'int8'
```
From here:

https://github.com/simonw/sqlite-utils/blob/577078fe01da6d876edda6f3ccbd1b5d074aeb6e/sqlite_utils/db.py#L208-L223

I'm not entirely sure how Homebrew ends up with a `numpy` that doesn't expose `np.int8` but I can fix it here, since this is an optional import anyway.
